version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
      java: corretto8
      
  build:
    commands:
      - npm install
      - gradle --stop
      - gradle wrapper
      - gradle --status
      - chmod +x ./gradlew
      - ls
      - ./gradlew assembleDebug

