version: 0.2

phases:
      
  build:
    commands:
      - npm install -g appcenter-cli
      
  post_build:
    commands:
      - appcenter login --token a30d1d90845599138da62c9abf8149642d3f64dd
      - appcenter codepush release-react -a NidhinKJC/AwesomeProject -d Staging
     
      

